#!/usr/bin/python3
from enum import Enum


class RotorWiring(Enum):
    I = "EKMFLGDQVZNTOWYHXUSPAIBRCJ"
    II = "AJDKSIRUXBLHWTMCQGZNPYFVOE"
    III = "BDFHJLCPRTXVZNYEIWGAKMUSQO"
    IV = "ESOVPZJAYQUIRHXLNFTGKDCMWB"
    V = "VZBRGITYUPSDNHLXAWMJQOFECK"
    VI = "JPGVOUMFYQBENHZRDKASXLICTW"
    VII = "NZJHGRCXMYSWBOUFAIVLPEKQDT"
    VIII = "FKQHTLXOCBJSPDZRAMEWNIUYGV"
    BETA = "LEYJVCNIXWPBQMDRTAKZGFUHOS"
    GAMMA = "FSOKANUERHMBTIYCWLQPZXVGJD"
